export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const LOAD_ARTICLES_REQUEST = "LOAD_ARTICLES_REQUEST";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const LOAD_ARTICLES_FAILURE = "LOAD_ARTICLES_FAILURE";

export const LOAD_ACTIVE_ARTICLES = "LOAD_ACTIVE_ARTICLES";
export const UPDATE_ACTIVE_ARTICLES = "UPDATED_ARTIVE_ARTICLES";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";
